#!/usr/bin/env bash
set -e

# Locate the repository root, regardless of the current working directory.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# Store samples generated by this example.
export OPENAI_LOGDIR="$REPO_ROOT/examples/3d_turbulence/outputs/sample_pcdm"
mkdir -p "$OPENAI_LOGDIR"

MODEL_PATH="$REPO_ROOT/examples/3d_turbulence/checkpoints/pcdm_fourier/ema_0.9999_800000.pt"

if [[ ! -f "$MODEL_PATH" ]]; then
    echo "Checkpoint not found: $MODEL_PATH"
    echo "Please download the pretrained PCDM-Fourier checkpoint as described in the README."
    exit 1
fi

DATA_FLAGS="--depth_size 64"
MODEL_FLAGS="--dims 3 --image_size 64 --in_channels 3 --num_channels 32 --num_res_blocks 2 --attention_resolutions 128 --channel_mult 1,2,4,8"
DIFFUSION_FLAGS="--constraint_name 3d_full --diffusion_steps 2000 --noise_schedule linear"
SAMPLE_FLAGS="--num_samples 2 --batch_size 1 --model_path $MODEL_PATH --seed 0"

# Use one GPU by default; override with NUM_GPUS=<number>.
NUM_GPUS="${NUM_GPUS:-1}"

if [[ "$NUM_GPUS" -eq 1 ]]; then
    python scripts/turb3d/turb3d_sample.py $DATA_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS $SAMPLE_FLAGS
else
    mpiexec -n "$NUM_GPUS" python scripts/turb3d/turb3d_sample.py $DATA_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS $SAMPLE_FLAGS
fi
