#!/usr/bin/env bash
set -e

# Locate the repository root, regardless of the current working directory.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# Store logs and checkpoints generated by this example.
export OPENAI_LOGDIR="$REPO_ROOT/examples/3d_turbulence/outputs/train_pcdm"
mkdir -p "$OPENAI_LOGDIR"

DATA_FLAGS="--dataset_path datasets/Rot64_f64_diffusion-example.h5 --dataset_name train --depth_size 64 --periodic_shift True"
MODEL_FLAGS="--dims 3 --image_size 64 --in_channels 3 --num_channels 32 --num_res_blocks 2 --attention_resolutions 128 --channel_mult 1,2,4,8"
DIFFUSION_FLAGS="--constraint_name 3d_full --diffusion_steps 2000 --noise_schedule linear"
TRAIN_FLAGS="--lr 1e-4 --batch_size 1 --log_interval 1 --save_interval 5 --total_steps 5"

# Use one GPU by default; override with NUM_GPUS=<number>.
NUM_GPUS="${NUM_GPUS:-1}"

if [[ "$NUM_GPUS" -eq 1 ]]; then
    python scripts/turb3d/turb3d_train.py $DATA_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS
else
    mpiexec -n "$NUM_GPUS" python scripts/turb3d/turb3d_train.py $DATA_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS
fi
