#!/usr/bin/env bash
set -e

# Locate the repository root, regardless of the current working directory.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# Store samples generated by this example.
export OPENAI_LOGDIR="$REPO_ROOT/examples/lagrangian_generation/outputs/sample_unet"
mkdir -p "$OPENAI_LOGDIR"

MODEL_PATH="$REPO_ROOT/examples/lagrangian_generation/checkpoints/unet/unconditional/ema_0.9999_400000.pt"

if [[ ! -f "$MODEL_PATH" ]]; then
    echo "Checkpoint not found: $MODEL_PATH"
    echo "Please download the pretrained DM-3c checkpoint as described in the README."
    exit 1
fi

SAMPLE_FLAGS="--num_samples 16 --batch_size 8 --model_path $MODEL_PATH"
MODEL_FLAGS="--dims 1 --image_size 2000 --in_channels 3 --num_channels 128 --num_res_blocks 3 --attention_resolutions 250,125 --channel_mult 1,1,2,3,4"
DIFFUSION_FLAGS="--diffusion_steps 800 --noise_schedule tanh6,1"

# Use one GPU by default; override with NUM_GPUS=<number>.
NUM_GPUS="${NUM_GPUS:-1}"

if [[ "$NUM_GPUS" -eq 1 ]]; then
    python scripts/turb/turb_sample.py $SAMPLE_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS
else
    mpiexec -n "$NUM_GPUS" python scripts/turb/turb_sample.py $SAMPLE_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS
fi
