#!/usr/bin/env bash
set -e

# Locate the repository root, regardless of the current working directory.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# Store logs and checkpoints generated by this example.
export OPENAI_LOGDIR="$REPO_ROOT/examples/lagrangian_generation/outputs/train_unet"
mkdir -p "$OPENAI_LOGDIR"

DATA_FLAGS="--dataset_path dataset/Lagr_u3c_diffusion-example.h5 --dataset_name train"
MODEL_FLAGS="--dims 1 --image_size 2000 --in_channels 3 --num_channels 128 --num_res_blocks 3 --attention_resolutions 250,125 --channel_mult 1,1,2,3,4"
DIFFUSION_FLAGS="--diffusion_steps 800 --noise_schedule tanh6,1"
TRAIN_FLAGS="--lr 1e-4 --batch_size 8 --log_interval 1 --save_interval 5 --total_steps 5"

# Use one GPU by default; override with NUM_GPUS=<number>.
NUM_GPUS="${NUM_GPUS:-1}"

if [[ "$NUM_GPUS" -eq 1 ]]; then
    python scripts/turb/turb_train.py $DATA_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS
else
    mpiexec -n "$NUM_GPUS" python scripts/turb/turb_train.py $DATA_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS
fi
