#!/usr/bin/env bash
set -e

# Locate the repository root, regardless of the current working directory.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# Store reconstructions generated by this example.
export OPENAI_LOGDIR="$REPO_ROOT/examples/lagrangian_reconstruction/outputs/reconstruct_dps"
mkdir -p "$OPENAI_LOGDIR"

MODEL_PATH="$REPO_ROOT/examples/lagrangian_reconstruction/checkpoints/prior/ema_0.9999_250000.pt"

if [[ ! -f "$MODEL_PATH" ]]; then
    echo "Checkpoint not found: $MODEL_PATH"
    echo "Please download the pretrained unconditional prior checkpoint as described in the README."
    exit 1
fi

DATA_FLAGS="--mask_mode center1d500 --dataset_path datasets/Lagr_u3c_diffusion-example.h5 --dataset_name train"
MODEL_FLAGS="--dims 1 --image_size 2000 --in_channels 3 --num_channels 128 --num_res_blocks 3 --attention_resolutions 250,125 --channel_mult 1,1,2,3,4"
DIFFUSION_FLAGS="--diffusion_steps 800 --noise_schedule tanh6,1"
SAMPLE_FLAGS="--num_samples 16 --batch_size 8 --model_path $MODEL_PATH --seed 0"
GUIDANCE_FLAGS="--guidance_name dps --guidance_strength 64.0"

# Use one GPU by default; override with NUM_GPUS=<number>.
NUM_GPUS="${NUM_GPUS:-1}"

if [[ "$NUM_GPUS" -eq 1 ]]; then
    python scripts/tfg/tfg_sample.py $DATA_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS $SAMPLE_FLAGS $GUIDANCE_FLAGS
else
    mpiexec -n "$NUM_GPUS" python scripts/tfg/tfg_sample.py $DATA_FLAGS $MODEL_FLAGS $DIFFUSION_FLAGS $SAMPLE_FLAGS $GUIDANCE_FLAGS

    echo "For multi-GPU reconstruction, restore the dataset-index correspondence using utils.parallel_utils.reverse_gpu_parallel_indices."
fi
